#!/usr/bin/env bash
# job-mode — isolated work profile (roadmap P2)
#
# One command to enter/leave "work mode": a dedicated git identity, no
# personal cloud sync, and a separate (calmer) theme. Everything is
# reversible via `job-mode off` and idempotent.
#
# Usage:
#   job-mode.sh on     # enter work mode (writes ~/.config/shesh/job-mode.env
#                      #   + git identity include; stops personal sync units)
#   job-mode.sh off    # leave work mode (removes the above, restores sync)
#   job-mode.sh status # print current mode and what would change
#
# Design: nothing is deleted — mode state lives in one small env file;
# git identity is injected via includeIf so personal repos keep their own
# identity. No secrets, no cloud, no sudo needed.
set -euo pipefail

STATE_DIR="${STATE_DIR:-$HOME/.config/shesh}"
MODE_FILE="$STATE_DIR/job-mode.env"
GIT_IDENTITY_FILE="$STATE_DIR/git-work-identity"
GIT_INCLUDE="$STATE_DIR/gitconfig-work"
PERSONAL_SYNC_UNITS=("vdirsyncer.timer" "restic-backup.timer" "shesh-backup.timer")

work_identity="${WORK_GIT_NAME:-Work}"
work_email="${WORK_GIT_EMAIL:-work@example.com}"
work_theme="${WORK_THEME:-dark-calm}"

usage() { sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

write_git_identity() {
  mkdir -p "$STATE_DIR"
  cat > "$GIT_IDENTITY_FILE" <<EOF
[user]
	name = $work_identity
	email = $work_email
EOF
  cat > "$GIT_INCLUDE" <<EOF
# Auto-generated by job-mode.sh — removed by 'job-mode off'
[includeIf "gitdir:**/work/**"]
	path = $GIT_IDENTITY_FILE
[includeIf "gitdir:**/*work*/**"]
	path = $GIT_IDENTITY_FILE
EOF
  # git auto-includes ~/.config/git/config; wire the work include there
  mkdir -p "$HOME/.config/git"
  touch "$HOME/.config/git/config"
  if ! grep -q "job-mode" "$HOME/.config/git/config" 2>/dev/null; then
    cat >> "$HOME/.config/git/config" <<EOF

# job-mode: work identity for work paths
[includeIf "gitdir:**/work/**"]
	path = $GIT_IDENTITY_FILE
EOF
  fi
}

remove_git_identity() {
  rm -f "$GIT_IDENTITY_FILE" "$GIT_INCLUDE"
  # strip the block we added from ~/.config/git/config (idempotent)
  sed -i '/# job-mode: work identity for work paths/,$d' "$HOME/.config/git/config" 2>/dev/null || true
}

# A unit that is absent or already stopped is the desired end state, not a
# failure. Anything else is reported: `|| true` would hide a real fault.
_ignore_missing_unit() {  # _ignore_missing_unit <action> <unit>
  local action="$1" unit="$2" rc=0 out
  out=$(systemctl --user "$action" "$unit" 2>&1) || rc=$?
  if [ "$rc" -ne 0 ] && ! printf '%s' "$out" | grep -qiE 'not loaded|not found|no such'; then
    printf 'warning: systemctl %s %s failed (rc=%s): %s\n' \
      "$action" "$unit" "$rc" "$out" >&2
  fi
}

stop_personal_sync() {
  for unit in "${PERSONAL_SYNC_UNITS[@]}"; do
    _ignore_missing_unit stop "$unit"
    _ignore_missing_unit disable "$unit"
  done
}

start_personal_sync() {
  for unit in "${PERSONAL_SYNC_UNITS[@]}"; do
    _ignore_missing_unit "enable --now" "$unit"
  done
}

switch_theme() {
  # Apply via the Hyprland theme wrapper if present; else no-op (mode env
  # still records the intent and other tools can read it).
  if command -v shesh-theme >/dev/null 2>&1; then
    if ! shesh-theme set "$work_theme" 2>&1; then
      printf 'warning: shesh-theme set %s failed; intent recorded anyway\n' \
        "$work_theme" >&2
    fi
  fi
}

do_on() {
  write_git_identity
  stop_personal_sync
  switch_theme
  cat > "$MODE_FILE" <<EOF
job_mode=on
work_git_name=$work_identity
work_git_email=$work_email
work_theme=$work_theme
EOF
  echo "job-mode ON (git identity '$work_identity <$work_email>', personal sync paused)"
}

do_off() {
  remove_git_identity
  start_personal_sync
  rm -f "$MODE_FILE"
  echo "job-mode OFF (personal sync restored)"
}

do_status() {
  if [ -f "$MODE_FILE" ]; then
    echo "job-mode: ON"
    cat "$MODE_FILE"
    echo "git work identity: $([ -f "$GIT_IDENTITY_FILE" ] && echo present || echo missing)"
  else
    echo "job-mode: OFF"
  fi
  echo "personal sync units: ${PERSONAL_SYNC_UNITS[*]}"
}

case "${1:-}" in
  on) do_on ;;
  off) do_off ;;
  status) do_status ;;
  -h|--help) usage 0 ;;
  *) usage 1 ;;
esac
